name: 'qversity'
version: '1.0.0'
config-version: 2

profile: 'qversity'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  qversity:
    # Silver layer - cleaned and transformed data
    silver:
      +materialized: table
      +schema: silver
      silver_cleaned_customers:
        enabled: true
      silver_qversity_engagement:
        enabled: false

    # Bronze layer - raw data models (Disabled here)
    bronze:
      bronze_qversity_interactions:
        enabled: false

    # Gold layer - business-ready data marts (Disabled here)
    gold:
      gold_qversity_analytics:
        enabled: false

seeds:
  qversity:
    +schema: raw
    mappings:
      +enabled: true