name: 'qversity'
version: '1.0.0'
config-version: 2

profile: 'qversity'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  qversity:
    silver:
      +materialized: table
      +schema: silver
      silver_cleaned_customers:
        enabled: true

    bronze:

    gold:
      +materialized: table
      +schema: gold

seeds:
  qversity:
    +schema: raw
    mappings:
      +enabled: true